# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiostream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audiostream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61udiostream.proto\"\x1c\n\x05\x43hunk\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\"\'\n\rStreamReceipt\x12\x16\n\x0estatus_message\x18\x01 \x01(\t2:\n\rAudioStreamer\x12)\n\x0bStreamAudio\x12\x06.Chunk\x1a\x0e.StreamReceipt\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiostream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=21
  _globals['_CHUNK']._serialized_end=49
  _globals['_STREAMRECEIPT']._serialized_start=51
  _globals['_STREAMRECEIPT']._serialized_end=90
  _globals['_AUDIOSTREAMER']._serialized_start=92
  _globals['_AUDIOSTREAMER']._serialized_end=150
# @@protoc_insertion_point(module_scope)
