# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audiostream.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'audiostream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61udiostream.proto\"!\n\nAudioChunk\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\"\'\n\rStreamReceipt\x12\x16\n\x0estatus_message\x18\x01 \x01(\t2?\n\rAudioStreamer\x12.\n\x0bStreamAudio\x12\x0b.AudioChunk\x1a\x0e.StreamReceipt\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiostream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=21
  _globals['_AUDIOCHUNK']._serialized_end=54
  _globals['_STREAMRECEIPT']._serialized_start=56
  _globals['_STREAMRECEIPT']._serialized_end=95
  _globals['_AUDIOSTREAMER']._serialized_start=97
  _globals['_AUDIOSTREAMER']._serialized_end=160
# @@protoc_insertion_point(module_scope)
